### ISSUE TITLE
Following DAVE install/build wiki does not lead to successful example simulation execution on fresh builds

### ISSUE THREAD

**Issue by BOSS-CC** [Field-Robotics-Lab/dave#159]
On a fresh build of a DAVE system running Ubuntu 20.04 and ROS Noetic:

`roslaunch dave_demo_launch dave_demo.launch`

launches a simulation environment within Gazebo, however the simulated vehicle appears to idle brokenly within the environment.

Along the same lines, regarding https://github.com/Field-Robotics-Lab/dave/wiki/Glider-Models: (dated 24 Sept 2020)

`roslaunch uuv_dave gliders_demo.launch paused:=true`

returns:

`RLException: [gliders_demo.launch] is neither a launch file in package [uuv_dave] nor is [uuv_dave] a launch file name`

and in fact `uuv_dave` appears to only contain:

`boss@boss-ThinkPad-P53:~/uuv_ws$ roslaunch uuv_dave`
`joy_thrusterop.launch       record_demo.launch          smilodon_standalone.launch`

Thus I'm uncertain how to follow the wiki to explore the DAVE examples, and am unable to determine if I have failed a successful installation/build of DAVE on my system because things are not where they should be or if the development of DAVE (& ROS) has outpaced the updating of the wiki because things have been simply moved elsewhere but are still fully functional.

This issue has been replicated on another fresh system by a more experienced ROS user than I.

**Comment by woensug-choi** [comment]
@BOSS-CC Yes, the inertial is the problem. It is the correct guess. Changing the line https://github.com/Field-Robotics-Lab/dave/blob/c6e3d923760e787ee9d7c49c67e767f1457779a8/urdf/robots/glider_description/urdf/glider_slocum.xacro#L59 to a more realistic inertia values will solve the unstableness of the physics engine behind it.

I've made a new branch so that you can test. It's `slocum_example` branch and the new launch command with only slocum glider with new inertial values is 'roslaunch dave_demo_launch dave_glider_slocum_demo.launch paused:=true`.

But, the launch file included in the `dave` repository callback the `uuv_underwater_object_ros_plugin` library which does not include any physical parameters of the glider kinematics characteristics (moving mass and buoyancy pump). In order to utilize those, you may need to use [`hybrid_glider_whoi` repo](https://github.com/Field-Robotics-Lab/glider_hybrid_whoi). It includes source code for `kinematics_ros_plugin` library.

And yes, you need a joystick to control the vehicle. Unless you design your own control script.

**Comment by woensug-choi** [comment]
Closing this issue has been without any response for 20 days. I hope things worked out for you. If not, comment here, and I will revive this.
