### ISSUE TITLE
Plans to migrate Project DAVE to ROS2?

### ISSUE THREAD

**Issue by JSaunders97** [Field-Robotics-Lab/dave#262]
Hi, 

I was just wondering if there are plans to migrate Project DAVE to ROS2 in the future?

Thanks!

**Comment by mabelzhang** [comment]
Hi, I don't have the authority to answer this in the absolute sense. But as far as I'm aware, the project has not received additional funding to go forward.

**Comment by mabelzhang** [comment]
There are multiple projects from Open Robotics targeting ROS 2 and the [new Gazebo](https://gazebosim.org/), which has native plugins for marine features, rather than third-party plugins. Check out [LRAUV](https://github.com/osrf/lrauv/), [WEC](https://github.com/osrf/mbari_wec) for underwater, and [VRX](https://github.com/osrf/vrx) and [MBZIRC](https://github.com/osrf/mbzirc) for surface vehicles.

I will close this as the question has been answered. Feel free to reopen if there are related followup questions.
